# Generated by Django 4.2 on 2023-04-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0004_genre_song_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='musiclibrary.genre'),
        ),
    ]
